/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DicomView: typeof import('./src/components/DicomView.vue')['default']
    'DicomView (ASUSZENBOOK の競合コピー 20240820)': typeof import('./src/components/DicomView (ASUSZENBOOK の競合コピー 2024-08-20).vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageBox: typeof import('./src/components/ImageBox.vue')['default']
    NiftiView: typeof import('./src/components/NiftiView.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}
